"""Mô tả thay đổi

Revision ID: 00058633f59a
Revises: f90ab53ca43e
Create Date: 2025-08-09 16:04:11.266950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '00058633f59a'
down_revision: Union[str, Sequence[str], None] = 'f90ab53ca43e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('payer_id', sa.Uuid(), nullable=False),
    sa.Column('payee_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('method', sa.Enum('CASH', 'WALLET', name='transactionmethod'), nullable=False),
    sa.Column('status', sa.Enum('SUCCESSFUL', 'FAILED', 'PENDING', name='transactionstatus'), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['payee_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['payer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_order_id'), 'transaction', ['order_id'], unique=True)
    op.create_index(op.f('ix_transaction_payee_id'), 'transaction', ['payee_id'], unique=False)
    op.create_index(op.f('ix_transaction_payer_id'), 'transaction', ['payer_id'], unique=False)
    op.add_column('order', sa.Column('total_amount_paid', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'total_amount_paid')
    op.drop_index(op.f('ix_transaction_payer_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_payee_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_order_id'), table_name='transaction')
    op.drop_table('transaction')
    # ### end Alembic commands ###
