"""add cascading delete for notification_id in noti_user

Revision ID: 1c7c02c6e0a5
Revises: 7138eb441180
Create Date: 2025-09-08 13:59:30.195596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '1c7c02c6e0a5'
down_revision: Union[str, Sequence[str], None] = '7138eb441180'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('noti_user_notification_id_fkey'), 'noti_user', type_='foreignkey')
    op.create_foreign_key(None, 'noti_user', 'notification', ['notification_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'noti_user', type_='foreignkey')
    op.create_foreign_key(op.f('noti_user_notification_id_fkey'), 'noti_user', 'notification', ['notification_id'], ['id'])
    # ### end Alembic commands ###
