"""Add current location of collector

Revision ID: 2faf2cce0fdc
Revises: 44ee385b221c
Create Date: 2025-08-24 16:31:46.742142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = '2faf2cce0fdc'
down_revision: Union[str, Sequence[str], None] = '44ee385b221c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('current_location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.execute('CREATE INDEX IF NOT EXISTS idx_user_current_location ON "user" USING gist (current_location)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_current_location', table_name='user', postgresql_using='gist')
    op.drop_column('user', 'current_location')
   
