"""update scrapCategory

Revision ID: 3671dc91e666
Revises: 88056839676e
Create Date: 2025-07-31 23:32:09.455443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '3671dc91e666'
down_revision: Union[str, Sequence[str], None] = '88056839676e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scrapcategory', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.add_column('scrapcategory', sa.Column('last_updated_by', sa.Uuid(), nullable=True))
    op.alter_column('scrapcategory', 'estimated_price_per_unit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.create_foreign_key(None, 'scrapcategory', 'user', ['last_updated_by'], ['id'])
    op.create_foreign_key(None, 'scrapcategory', 'user', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scrapcategory', type_='foreignkey')
    op.drop_constraint(None, 'scrapcategory', type_='foreignkey')
    op.alter_column('scrapcategory', 'estimated_price_per_unit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('scrapcategory', 'last_updated_by')
    op.drop_column('scrapcategory', 'created_by')
    # ### end Alembic commands ###
