"""update table user

Revision ID: 59db12976b19
Revises: 05b05620b14b
Create Date: 2025-07-30 16:12:04.066269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '59db12976b19'
down_revision: Union[str, Sequence[str], None] = '05b05620b14b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.Enum('ADMIN', 'USER', 'COLLECTOR', 'BUSINESS', name='userrole'), nullable=False))
    op.drop_column('user', 'role_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role_id', postgresql.ENUM('ADMIN', 'USER', 'COLLECTOR', 'BUSINESS', name='userrole'), autoincrement=False, nullable=False))
    op.drop_column('user', 'role')
    # ### end Alembic commands ###
