"""update user cascading delete

Revision ID: 65a8cb88d80e
Revises: a82ab2e60547
Create Date: 2025-08-26 12:43:34.372112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '65a8cb88d80e'
down_revision: Union[str, Sequence[str], None] = 'a82ab2e60547'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('scrapcategory_last_updated_by_fkey'), 'scrapcategory', type_='foreignkey')
    op.drop_constraint(op.f('scrapcategory_created_by_fkey'), 'scrapcategory', type_='foreignkey')
    op.create_foreign_key(None, 'scrapcategory', 'user', ['created_by'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'scrapcategory', 'user', ['last_updated_by'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_unique_constraint(None, 'user', ['hashed_password'])
    op.drop_column('user', 'email')
    op.drop_column('user', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('full_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.drop_constraint(None, 'scrapcategory', type_='foreignkey')
    op.drop_constraint(None, 'scrapcategory', type_='foreignkey')
    op.create_foreign_key(op.f('scrapcategory_created_by_fkey'), 'scrapcategory', 'user', ['created_by'], ['id'])
    op.create_foreign_key(op.f('scrapcategory_last_updated_by_fkey'), 'scrapcategory', 'user', ['last_updated_by'], ['id'])
    # ### end Alembic commands ###
