"""add table conversation

Revision ID: 6d1f61e51319
Revises: 93dca1f4e3ae
Create Date: 2025-09-04 19:28:44.098316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d1f61e51319'
down_revision: Union[str, Sequence[str], None] = '93dca1f4e3ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user1_id', sa.Uuid(), nullable=False),
    sa.Column('user2_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user1_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user2_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_id'), 'conversation', ['id'], unique=False)
    op.create_index(op.f('ix_conversation_user1_id'), 'conversation', ['user1_id'], unique=False)
    op.create_index(op.f('ix_conversation_user2_id'), 'conversation', ['user2_id'], unique=False)
    op.add_column('message', sa.Column('conversation_id', sa.Uuid(), nullable=False))
    op.add_column('message', sa.Column('is_read', sa.Boolean(), nullable=False))
    op.add_column('message', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_index(op.f('ix_message_receiver_id'), table_name='message')
    op.create_index(op.f('ix_message_conversation_id'), 'message', ['conversation_id'], unique=False)
    op.drop_constraint(op.f('message_receiver_id_fkey'), 'message', type_='foreignkey')
    op.create_foreign_key(None, 'message', 'conversation', ['conversation_id'], ['id'])
    op.drop_column('message', 'receiver_id')
    op.drop_column('message', 'timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('message', sa.Column('receiver_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.create_foreign_key(op.f('message_receiver_id_fkey'), 'message', 'user', ['receiver_id'], ['id'])
    op.drop_index(op.f('ix_message_conversation_id'), table_name='message')
    op.create_index(op.f('ix_message_receiver_id'), 'message', ['receiver_id'], unique=False)
    op.drop_column('message', 'created_at')
    op.drop_column('message', 'is_read')
    op.drop_column('message', 'conversation_id')
    op.drop_index(op.f('ix_conversation_user2_id'), table_name='conversation')
    op.drop_index(op.f('ix_conversation_user1_id'), table_name='conversation')
    op.drop_index(op.f('ix_conversation_id'), table_name='conversation')
    op.drop_table('conversation')
    # ### end Alembic commands ###
