"""cascading delete for notiuser

Revision ID: 7138eb441180
Revises: 044ca74213ab
Create Date: 2025-09-08 11:40:22.422398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '7138eb441180'
down_revision: Union[str, Sequence[str], None] = '044ca74213ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'is_read')
    op.drop_constraint(op.f('noti_user_user_id_fkey'), 'noti_user', type_='foreignkey')
    op.create_foreign_key(None, 'noti_user', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'noti_user', type_='foreignkey')
    op.create_foreign_key(op.f('noti_user_user_id_fkey'), 'noti_user', 'user', ['user_id'], ['id'])
    op.add_column('message', sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
