"""update user attributes

Revision ID: 7faac493cf35
Revises: 65a8cb88d80e
Create Date: 2025-08-26 12:46:05.610743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '7faac493cf35'
down_revision: Union[str, Sequence[str], None] = '65a8cb88d80e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False))
    op.add_column('user', sa.Column('avt_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('user', sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False))
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_column('user', 'email')
    op.drop_column('user', 'avt_url')
    op.drop_column('user', 'full_name')
    # ### end Alembic commands ###
