"""add 2 img_url into order

Revision ID: 93dca1f4e3ae
Revises: 985af2a5aedc
Create Date: 2025-09-03 17:06:11.321057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '93dca1f4e3ae'
down_revision: Union[str, Sequence[str], None] = '985af2a5aedc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('img_url1', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('order', sa.Column('img_url2', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'img_url2')
    op.drop_column('order', 'img_url1')
    # ### end Alembic commands ###
