"""add slug to category

Revision ID: a708edae86cb
Revises: ea03c348a2c2
Create Date: 2025-08-04 20:34:13.702416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'a708edae86cb'
down_revision: Union[str, Sequence[str], None] = 'ea03c348a2c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('street', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('district', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('ward', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('street_address', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_address_user_id'), 'address', ['user_id'], unique=False)
    op.add_column('order', sa.Column('address_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_order_address_id'), 'order', ['address_id'], unique=False)
    op.create_index(op.f('ix_order_collector_id'), 'order', ['collector_id'], unique=False)
    op.create_index(op.f('ix_order_owner_id'), 'order', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'order', 'address', ['address_id'], ['id'])
    op.create_index(op.f('ix_orderitem_category_id'), 'orderitem', ['category_id'], unique=False)
    op.create_index(op.f('ix_orderitem_order_id'), 'orderitem', ['order_id'], unique=False)
    op.create_index(op.f('ix_review_order_id'), 'review', ['order_id'], unique=False)
    op.create_index(op.f('ix_review_user_id'), 'review', ['user_id'], unique=False)
    op.add_column('scrapcategory', sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False))
    op.alter_column('scrapcategory', 'created_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('scrapcategory', 'last_updated_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index(op.f('ix_scrapcategory_slug'), 'scrapcategory', ['slug'], unique=True)
    op.drop_constraint(op.f('user_phone_number_key'), 'user', type_='unique')
    op.create_index(op.f('ix_user_phone_number'), 'user', ['phone_number'], unique=True)
    op.drop_column('user', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_user_phone_number'), table_name='user')
    op.create_unique_constraint(op.f('user_phone_number_key'), 'user', ['phone_number'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_scrapcategory_slug'), table_name='scrapcategory')
    op.alter_column('scrapcategory', 'last_updated_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('scrapcategory', 'created_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('scrapcategory', 'slug')
    op.drop_index(op.f('ix_review_user_id'), table_name='review')
    op.drop_index(op.f('ix_review_order_id'), table_name='review')
    op.drop_index(op.f('ix_orderitem_order_id'), table_name='orderitem')
    op.drop_index(op.f('ix_orderitem_category_id'), table_name='orderitem')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_index(op.f('ix_order_owner_id'), table_name='order')
    op.drop_index(op.f('ix_order_collector_id'), table_name='order')
    op.drop_index(op.f('ix_order_address_id'), table_name='order')
    op.drop_column('order', 'address_id')
    op.drop_index(op.f('ix_address_user_id'), table_name='address')
    op.drop_table('address')
    # ### end Alembic commands ###
