"""update user: gender birthday and email

Revision ID: a82ab2e60547
Revises: 2faf2cce0fdc
Create Date: 2025-08-25 17:37:57.496510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'a82ab2e60547'
down_revision: Union[str, Sequence[str], None] = '2faf2cce0fdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True))
    op.add_column('user', sa.Column('birth_date', sa.Date(), nullable=True))
    op.add_column('user', sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_column('user', 'email')
    op.drop_column('user', 'birth_date')
    op.drop_column('user', 'gender')
    # ### end Alembic commands ###
