"""address into order

Revision ID: a8ff23a82374
Revises: a708edae86cb
Create Date: 2025-08-05 15:00:12.412656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'a8ff23a82374'
down_revision: Union[str, Sequence[str], None] = 'a708edae86cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('is_default', sa.Boolean(), nullable=False))
    op.add_column('order', sa.Column('pickup_address', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('order', sa.Column('pickup_latitude', sa.Float(), nullable=True))
    op.add_column('order', sa.Column('pickup_longitude', sa.Float(), nullable=True))
    op.drop_index(op.f('ix_order_address_id'), table_name='order')
    op.drop_constraint(op.f('order_address_id_fkey'), 'order', type_='foreignkey')
    op.drop_column('order', 'address_id')
    op.drop_column('order', 'total_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('total_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('order', sa.Column('address_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('order_address_id_fkey'), 'order', 'address', ['address_id'], ['id'])
    op.create_index(op.f('ix_order_address_id'), 'order', ['address_id'], unique=False)
    op.drop_column('order', 'pickup_longitude')
    op.drop_column('order', 'pickup_latitude')
    op.drop_column('order', 'pickup_address')
    op.drop_column('address', 'is_default')
    # ### end Alembic commands ###
