"""add title for noti

Revision ID: cb30e48645cc
Revises: d6464729e1e4
Create Date: 2025-08-30 13:58:54.066779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'cb30e48645cc'
down_revision: Union[str, Sequence[str], None] = 'd6464729e1e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'title')
    # ### end Alembic commands ###
