name: Deploy to VPS with Docker

on:
    push:
        branches:
            - main
        paths:
            - "backend/**"
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            # Bước 1: Lấy mã nguồn về
            - name: Checkout code
              uses: actions/checkout@v3

            # Bước 2: Thiết lập kết nối SSH (giữ nguyên như trước)
            - name: Set up SSH
              run: |
                  mkdir -p ~/.ssh/
                  echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa
                  ssh-keyscan -H "${{ secrets.VPS_IP }}" >> ~/.ssh/known_hosts

            # Bước 3: Build và triển khai với Docker Compose trên VPS
            - name: Deploy to VPS
              run: |
                  ssh -tt ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} << 'EOF'
                    cd /home/dev/Final-mobile
                    git pull origin main
                    cd backend
                    docker compose up -d --build
                    docker image prune -f
                  EOF
