name: Deploy to VPS with Docker

on:
    push:
        branches:
            - main
        paths:
            - "backend/**"
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Deploy to VPS via SSH
              uses: appleboy/ssh-action@v0.1.10
              with:
                  host: ${{ secrets.VPS_IP }}
                  username: ${{ secrets.VPS_USERNAME }}
                  key: ${{ secrets.VPS_SSH_KEY }}
                  script: |
                      cd /home/dev/Final-mobile/backend
                      docker compose down
                      git pull origin main
                      cd backend
                      docker compose build
                      docker compose run --rm migrate
                      docker compose up -d --remove-orphans
                      docker builder prune -f
                      docker image prune -f
