# # .github/workflows/backend-ci.yml

# name: Backend CI

# on:
#   push:
#     paths:
#       - 'backend/**'
#   pull_request:
#     paths:
#       - 'backend/**'

# jobs:
#   test:
#     name: Run Backend Tests
#     runs-on: ubuntu-latest

#     defaults:
#       run:
#         working-directory: backend

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Create .env file for services
        
#         run: |
#           echo "POSTGRES_USER=testuser" > .env
#           echo "POSTGRES_PASSWORD=testpass" >> .env
#           echo "POSTGRES_HOST=db" >> .env
#           echo "POSTGRES_PORT=5432" >> .env
#           echo "POSTGRES_DB=vechai_db_test" >> .env
#           echo "PROJECT_NAME=Vechai CI Test" >> .env
#           echo "API_STR=/api/v1" >> .env
#           echo "DATABASE_URL=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}" >> .env
          
#       - name: Start All Services
        
#         run: docker compose up -d --wait

#       - name: Show running containers
        
#         run: docker compose ps

#       - name: Run migrations
#         run: docker compose exec migrate alembic upgrade head

#       - name: Run backend tests
#         run: PYTEST_ENV_FILE=.env.ci.test docker compose run web pytest