name: Backend CI

on:
  push:
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'

jobs:
  test:
    name: Run Backend Tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install docker-compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.6/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      - name: Set up Docker Compose
        run: docker-compose up -d db

      - name: Wait for DB to be healthy
        run: |
          for i in {1..30}; do
            docker-compose exec db pg_isready -U $POSTGRES_USER -d $POSTGRES_DB && break
            sleep 2
          done

      - name: Run migrations
        run: docker-compose run migrate

      - name: Run backend tests
        run: docker-compose run web pytest
